### ISSUE TITLE
ERROR: No matching distribution found for torch==2.0.1+cu117

### ISSUE THREAD

**Issue by Ekanyani** [LLENN8/Virtual-AI-Imouto-Misaka-Chan#1]
![Screenshot_1](https://github.com/LLENN8/Virtual-AI-Imouto-Misaka-Chan/assets/109494951/fac173da-5247-47c9-8cd8-4f35cc4d9004)

**Comment by LLENN8** [comment]
![IMG-20230805-WA0022.jpg](https://github.com/LLENN8/Virtual-AI-Imouto-Misaka-Chan/assets/46107821/d720b011-2cf6-4802-893d-6af7a1fc67c9)

Thank you

It seems an error because pip did not find the appropriate torch. Try install from the command corresponding to the device on the following website
https://pytorch.org/
